const MyQueue = require ('./Queue')

const qq = new MyQueue (10)
qq.pushQ(4)
qq.pushQ(20)
qq.pushQ(399)
qq.pushQ(78)
qq.pushQ(5)
qq.pushQ(21)
qq.pushQ(400)
qq.pushQ(79)
qq.pushQ(6)
qq.pushQ(22)
qq.pushQ(501)
qq.pushQ(80)
// qq.popQ()
// qq.popQ()
console.log(qq)
console.log(qq.emptyQ())
console.log(qq.fullQ())
console.log(qq.peekQ())
console.log(qq.queue())

