const Stack = require ('./SQ')
const ThreeInOne = require ('./SQThree')


// let ss = new Stack (10)
// ss.push(5)
// ss.push(10)
// ss.pop()
// ss.pop()
// console.log(ss.empty())
// ss.push(12)
// ss.push(29)
// console.log(ss.peek())
// console.log(ss)
// console.log(ss.empty())

let s3 = new ThreeInOne(9)
console.log(s3.emptyempty())
s3.pushpush(4)
s3.pushpush(4)
s3.pushpush(4)
s3.pushpush(4)
s3.pushpush(4)
s3.pushpush(2)
s3.pushpush(9)
s3.pushpush(9)
s3.pushpush(15)
console.log(s3.pushpush(9))
console.log(s3)
console.log(s3.fullfull())
console.log(s3.peekpeek())
s3.poppop()
s3.poppop()
s3.poppop()
s3.poppop()
s3.poppop()
console.log(s3)

