const Stack = require ('./SQ')
const ThreeInOne = require ('./SQThree')

// const ss = Stack.fromValues(10, 33, 42, 14, 2, 6, 16)
// console.log(ss.min())

const sa = Stack.fromValues(10, 33, 42, 14, 2)
sa.pop()
console.log(sa)

// let s3 = new ThreeInOne(9)
// console.log(s3.emptyempty())
// s3.pushpush(4)
// s3.pushpush(4)
// s3.pushpush(4)
// s3.pushpush(4)
// s3.pushpush(4)
// s3.pushpush(2)
// s3.pushpush(9)
// s3.pushpush(9)
// s3.pushpush(15)
// console.log(s3.pushpush(9))
// console.log(s3)
// console.log(s3.fullfull())
// console.log(s3.peekpeek())
// s3.poppop()
// s3.poppop()
// s3.poppop()
// s3.poppop()
// s3.poppop()
// console.log(s3)

